### ISSUE TITLE
node_alive prefix when showing nodeName in /diagnostics

### ISSUE THREAD

**Issue by msadowski** [tue-robotics/node_alive#5]
Hi again!

I noticed that when you look at the /diagnostics topic the node name is prefixed with "node_alive". This is hardcoded in this line:

```
 statusMsg.name = "node_alive%s" % tracked_node
```

Does anyone know what's the reasoning behind this? It's trivial to strip this on the receiving side but I'm wondering if you run into any caveats with keeping unmodified node names?

**Comment by reinzor** [comment]
Hi, diagnostic names are rather arbitrary. Don't know why we have chosen this prefix exactly but most probably so that the common diagnostic tools can filter on name (e.g. diagnostic aggregater).

**Comment by msadowski** [comment]
@reinzor thanks for a quick answer. Do you think this would be feasible to have this prefix as a parameter or an argument in the node?

In my scenario, when using this package I'm looking to do some operations on nodes that are alive (for example fetch parameters). Optionally not having the prefix would allow me to directly work with the name from the status message.

If you think that's desirable I'd go for something like this:
```
rospy.get_param('status_prefix', 'node_alive')
```

That way we don't break the backwards compatibility for your cases because we will default to node_alive prefix but we allow the user to specify his own prefix (in my case that would be an empty string).

Happy to make a PR if you think it's desirable

**Comment by reinzor** [comment]
Seems like a good option to me and remain backwards compatibility. Please use local node parameters (`~`)

**Comment by msadowski** [comment]
Thanks for the merge!
