### ISSUE TITLE
Make a call to rospy.sleep depend on system timing

### ISSUE THREAD

**Issue by msadowski** [tue-robotics/node_alive#7]
Me again!

I have some new thoughts about the system (and as always more than happy to make a PR):
1. It could be a good idea to allow user to specify how much the best case* update rate for the topic (basically parametrizing the variable that is currently fixed to 5 in [this line](https://github.com/tue-robotics/node_alive/blob/c9e7e443d6b9cf6274470baff7ba08117fbce5e7/src/node_alive_server#L154))
2. Rosnode ping can take an awful lot of time to complete (I mentioned a bug [here](https://github.com/ros/ros_comm/issues/1516)). We could make the sleep vary depending on the time it took the rosnode ping to complete.

Scenario I think happens:
Let's assume one node causes a rosnode ping to timeout (with the fix I proposed in the PR it would mean that rosnode ping will give up trying to contact this node after 3 seconds).

This is how I'm expecting node_alive to behave:
- call rosnode ping [~3 sec to finish]
- publish to the topic (t=3) 
- sleep [5 seconds]
- call rosnode ping [~3 sec]
- publish to the topic (t=11) < ideally should be at t=8 to keep constant rate 

In more extreme cases, where rosnode ping takes over 5 seconds this sleep will add 5 seconds of unnecessary overhead.

**Comment by MatthijsBurgh** [comment]
This is accounted for by rospy.rate. It takes into account how much time has passed in the current iteration of the loop and sleeps till only the time needed to keep the loop rate.

So if you have 2 seconds(0,5 Hz), 1,5 seconds has passed, it only sleeps for 0,5 seconds.

So please create a PR in which you parameterize the rate and implement rospy.rate.

**Comment by MatthijsBurgh** [comment]
fixed by #8
